### PR TITLE
Milestone 5

### PR DESCRIPTION
**Pull request by kazumaki**
The goal of this milestone is to style our bookstore; We did it using CSS.

### CODE REVIEW

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello team  🌟

**Nice work on this project, but the following changes need to be done before moving on ⬇️** 

- Nice work so far, however, the design should match exactly the one provided in the requirements.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by kazumaki** [comment]
> # Changes required ♻️
> ### Hello team 🌟
> **Nice work on this project, but the following changes need to be done before moving on ⬇️**
> 
> * Nice work so far, however, the design should match exactly the one provided in the requirements.
> 
> ### _After making the required changes please submit a new code review request_
> ### Good luck! 🍀

The reviewer said that the project should match exactly the one provided in the requirements, but I disagree, I already contacted the reviewer through slack but since he doesn't answer me I'll ask for another code review and point the reasons for this based on microverse requirements.

micro-requirements

As you can see we can ignore non implemented features like comments as we did.
The second point is "Implement the styling of the different components based on the design", it says based on the design not to match exactly the same style.

Thank you,
Vinicius Campos

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED

Hi guys this design looks superb now :+1:  however I discovered a bug in the app when the page is loaded there is a book in the "self-improvement" category, this book does not show up if a filter is done with "self improvement" 

Step to reproduce:
1. Load page
2. Click on select dropdown
3. select "Self improvement" 

Nothing shows up but actually a book should show up. 

Please fix this and **request for another review** you could leave the design as it is now

**RAPHAEL NORIODE** :mask:

**Review by shloch — APPROVED** [review]
book

### Good to go...we can merge this

**Pull request merged**
